# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
