# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_polls', '0002_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='Nation', max_length=100),
        ),
    ]
