# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_polls', '0008_auto_20160912_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='count',
        ),
        migrations.AddField(
            model_name='player',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
