# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_polls', '0009_auto_20160912_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Comment Count'),
        ),
    ]
