# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_polls', '0011_enduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='favourite_players',
            field=models.CharField(default='', max_length=300),
        ),
    ]
