# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_polls', '0012_enduser_favourite_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='favourite_players',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
