# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_polls', '0013_auto_20160913_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='favourite_team',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='player_polls.Team'),
        ),
    ]
