# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_polls', '0014_auto_20160913_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='favourite_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_polls.Team'),
        ),
    ]
